<?php
require_once '../../config/auth.php';
requestMethod('GET');
try{ $db=getDB(); $adminView=(($_GET['admin']??'')==='true'||($_GET['admin']??'')==='1')&&isAdminUser(); $ownView=!$adminView && isLoggedIn() && !empty($_GET['user_id']) && (int)$_GET['user_id']===currentUserId(); $where=[]; $params=[]; if(!$adminView && !$ownView){$where[]='lr.is_approved=1';} elseif($adminView && isset($_GET['is_approved'])&&$_GET['is_approved']!==''){ $where[]='lr.is_approved=?'; $params[]=(int)$_GET['is_approved']; }
if(!empty($_GET['user_id'])){ $where[]='lr.user_id=?'; $params[]=(int)$_GET['user_id']; }
if(!empty($_GET['district_id'])){ $where[]='lr.district_id=?'; $params[]=(int)$_GET['district_id']; }
if(!empty($_GET['star_rating'])){ $where[]='lr.star_rating>=?'; $params[]=(int)$_GET['star_rating']; }
if(!empty($_GET['search'])){ $q='%'.trim($_GET['search']).'%'; $where[]='(lr.landlord_name LIKE ? OR lr.property_address LIKE ? OR lr.review_text LIKE ?)'; array_push($params,$q,$q,$q); }
if(!empty($_GET['area'])){ $q='%'.trim($_GET['area']).'%'; $where[]='lr.property_address LIKE ?'; $params[]=$q; }
$whereSql=$where?'WHERE '.implode(' AND ',$where):''; $stmt=$db->prepare("SELECT COUNT(*) AS total FROM landlord_reviews lr $whereSql"); $stmt->execute($params); $total=(int)$stmt->fetch()['total']; $page=max(1,(int)($_GET['page']??1)); $limit=min(50,max(1,(int)($_GET['limit']??20))); $offset=($page-1)*$limit;
$sql="SELECT lr.*, u.full_name AS reviewer_name, u.profile_picture, d.name AS district FROM landlord_reviews lr JOIN users u ON u.id=lr.user_id LEFT JOIN districts d ON d.id=lr.district_id $whereSql ORDER BY lr.created_at DESC LIMIT :limit OFFSET :offset"; $stmt=$db->prepare($sql); foreach($params as $i=>$v)$stmt->bindValue($i+1,$v); $stmt->bindValue(':limit',$limit,PDO::PARAM_INT); $stmt->bindValue(':offset',$offset,PDO::PARAM_INT); $stmt->execute(); $reviews=[]; foreach($stmt->fetchAll() as $r){ $reviews[]=['id'=>(int)$r['id'],'user_id'=>(int)$r['user_id'],'landlord_name'=>$r['landlord_name'],'property_address'=>$r['property_address'],'district_id'=>$r['district_id']?(int)$r['district_id']:null,'district'=>$r['district'],'star_rating'=>(int)$r['star_rating'],'is_recommended'=>(int)$r['is_recommended'],'review_text'=>$r['review_text'],'is_approved'=>(int)$r['is_approved'],'reviewer_name'=>$r['reviewer_name'],'profile_picture'=>$r['profile_picture'],'created_at'=>$r['created_at'],'updated_at'=>$r['updated_at']]; } jsonResponse(['success'=>true,'reviews'=>$reviews,'total'=>$total,'page'=>$page,'limit'=>$limit]); }catch(Throwable $e){ jsonError('Could not fetch reviews.',500); }
