<?php
require_once '../../config/auth.php';
requestMethod('POST');
requireLogin();
$data=getRequestData();
try{ $db=getDB(); $stmt=$db->prepare('SELECT id FROM roommate_profiles WHERE user_id=?'); $stmt->execute([currentUserId()]); $existing=$stmt->fetch();
$budgetMin=($data['budget_min']??'')!==''?(int)$data['budget_min']:null; $budgetMax=($data['budget_max']??'')!==''?(int)$data['budget_max']:null; $districtRaw=$data['district_id']??$data['district']??''; $districtId=null; if($districtRaw!==''){ if(is_numeric($districtRaw)) $districtId=(int)$districtRaw; else { $ds=$db->prepare('SELECT id FROM districts WHERE name=? LIMIT 1'); $ds->execute([$districtRaw]); $dr=$ds->fetch(); $districtId=$dr?(int)$dr['id']:null; } } $monthRaw=$data['move_in_month']??''; $month=null; if($monthRaw!==''){ if(is_numeric($monthRaw)) $month=(int)$monthRaw; else { $months=['january'=>1,'february'=>2,'march'=>3,'april'=>4,'may'=>5,'june'=>6,'july'=>7,'august'=>8,'september'=>9,'october'=>10,'november'=>11,'december'=>12]; $month=$months[strtolower(trim($monthRaw))]??null; } } $year=($data['move_in_year']??'')!==''?(int)$data['move_in_year']:null; $desc=trim($data['description']??'');
if($existing){ $profileId=(int)$existing['id']; $stmt=$db->prepare('UPDATE roommate_profiles SET budget_min=?,budget_max=?,district_id=?,move_in_month=?,move_in_year=?,description=?,profile_visible=1 WHERE id=?'); $stmt->execute([$budgetMin,$budgetMax,$districtId,$month,$year,$desc,$profileId]); } else { $stmt=$db->prepare('INSERT INTO roommate_profiles (user_id,budget_min,budget_max,district_id,move_in_month,move_in_year,description,is_published,profile_visible) VALUES (?,?,?,?,?,?,?,0,1)'); $stmt->execute([currentUserId(),$budgetMin,$budgetMax,$districtId,$month,$year,$desc]); $profileId=(int)$db->lastInsertId(); }
$db->prepare('DELETE FROM roommate_preferred_areas WHERE roommate_profile_id=?')->execute([$profileId]); $stmtA=$db->prepare('INSERT INTO roommate_preferred_areas (roommate_profile_id,area_id) VALUES (?,?)'); foreach(normalizeArray($data['area_ids']??$data['areas']??[]) as $aid){ if(is_numeric($aid)) { $stmtA->execute([$profileId,(int)$aid]); } else { $as=$db->prepare('SELECT id FROM areas WHERE name=? AND (? IS NULL OR district_id=?) LIMIT 1'); $as->execute([$aid,$districtId,$districtId]); $ar=$as->fetch(); if($ar) $stmtA->execute([$profileId,(int)$ar['id']]); } }
$db->prepare('DELETE FROM roommate_tags WHERE roommate_profile_id=?')->execute([$profileId]); $stmtT=$db->prepare('INSERT INTO roommate_tags (roommate_profile_id,tag_name) VALUES (?,?)'); foreach(normalizeArray($data['tags']??[]) as $tag){ $stmtT->execute([$profileId,trim($tag)]); }
if(parseBool($data['publish']??0)){ $db->prepare('UPDATE roommate_profiles SET is_published=1, profile_visible=1 WHERE id=?')->execute([$profileId]); } logActivity($db,currentUserId(),'update_roommate_profile','Updated roommate profile'); jsonResponse(['success'=>true,'profile_id'=>$profileId]); }catch(Throwable $e){ jsonError('Could not save roommate profile.',500); }
